### ISSUE TITLE
Docs in the website are not synced with this repo

### ISSUE THREAD

**Issue by WatheqAlshowaiter** [cpriego/valet-linux-docs#7]
For example I fixed `https` error after hours by the help of one comment 
https://github.com/cpriego/valet-linux/issues/233#issuecomment-677469719

I was planning to ad this to the docs but actually it was adding just in the repo, not in the site. I hope this fixed because so many problems should be fixed if they are shown in the docs.

### The section in the repo

https://github.com/cpriego/valet-linux-docs/blob/master/faq.md#issue-valet-secure-doesnt-work:~:text=to%20your%20network.-,Issue%20valet%20secure%20doesnt%20work%3F,-Solutions%3A

### The section is missing in the docs
https://cpriego.github.io/valet-linux/faq#any-other-tips:~:text=to%20your%20network.-,Any%20other%20tips%3F,-Oh%20yeah!%2C%20for

 @Adesin-fr @cpriego

**Comment by jmarcher** [comment]
It is fixed, the documentation is not hosted here anymore but in a new branch in the main repo: https://github.com/cpriego/valet-linux/tree/gh-pages

**Comment by WatheqAlshowaiter** [comment]
Thanks for responding @jmarcher
